-- Script de Criação do Banco de Dados para o Supabase (Centro Espírita União)
-- Limpeza prévia (se necessário regravar)
-- DROP TABLE IF EXISTS ceu_lancamentos CASCADE;
-- DROP TABLE IF EXISTS ceu_departamentos CASCADE;
-- DROP TABLE IF EXISTS ceu_arquivos_importados CASCADE;

-- 1. TABELA DE ARQUIVOS IMPORTADOS
CREATE TABLE ceu_arquivos_importados (
    id_codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    nome_arquivo TEXT NOT NULL,
    conta TEXT NOT NULL,
    mes_ano TEXT NOT NULL,
    saldo_inicial NUMERIC(15,2) DEFAULT 0.00,
    total_debitos NUMERIC(15,2) DEFAULT 0.00,
    total_creditos NUMERIC(15,2) DEFAULT 0.00,
    saldo_final NUMERIC(15,2) DEFAULT 0.00,
    data_importacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE DEPARTAMENTOS
CREATE TABLE ceu_departamentos (
    id_codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    tipo TEXT CHECK (tipo IN ('credito', 'debito', 'misto')) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE NOT NULL
);

-- Inserindo alguns departamentos padrão de exemplo
INSERT INTO ceu_departamentos (nome, tipo) VALUES 
('Dízimos e Doações', 'credito'),
('Promoções e Eventos', 'misto'),
('Contas de Consumo (Água/Luz/Net)', 'debito'),
('Manutenção e Obras', 'debito');

-- 3. TABELA DE LANÇAMENTOS (Extrato detalhado)
CREATE TABLE ceu_lancamentos (
    id_codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    
    id_arquivo_origem BIGINT NOT NULL,
    id_departamento BIGINT,
    
    status TEXT CHECK (status IN ('pendente', 'conciliado', 'finalizado')) DEFAULT 'pendente' NOT NULL,
    data_transacao DATE NOT NULL,
    historico_banco TEXT NOT NULL,
    detalhes_complementares TEXT,
    tipo_movimento TEXT CHECK (tipo_movimento IN ('Receita', 'Despesa')) NOT NULL,
    valor_absoluto NUMERIC(15,2) NOT NULL,
    
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    CONSTRAINT fk_arquivo
      FOREIGN KEY(id_arquivo_origem) 
      REFERENCES ceu_arquivos_importados(id_codigo)
      ON DELETE CASCADE,
      
    CONSTRAINT fk_departamento
      FOREIGN KEY(id_departamento) 
      REFERENCES ceu_departamentos(id_codigo)
      ON DELETE SET NULL
);

-- Ativa políticas de RLS para o Supabase (Segurança de acesso por API)
ALTER TABLE ceu_arquivos_importados ENABLE ROW LEVEL SECURITY;
ALTER TABLE ceu_departamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ceu_lancamentos ENABLE ROW LEVEL SECURITY;

-- Permite leitura e escrita anônima para testes/desenvolvimento
CREATE POLICY "Public Access" ON ceu_arquivos_importados FOR ALL USING (true);
CREATE POLICY "Public Access" ON ceu_departamentos FOR ALL USING (true);
CREATE POLICY "Public Access" ON ceu_lancamentos FOR ALL USING (true);
